### ISSUE TITLE
在控制台创建路由信息500

### ISSUE THREAD

**Issue by redgra0315** [alibaba/higress#1318]
使用的ingress 版本：v1.4.2
k8s 版本：1.28.3
安装方式：helm 

控制台创建路由信息报错：
![Uploading image.png…]()
![控制台报错信息](https://github.com/user-attachments/assets/f589479d-4d61-42f6-814d-2c1856f3592c)

错误信息：
服务器内部错误
错误详情（错误码：500）
Method: post
RequestURL: http://hd-demo-higress.ee4m.com.cn/v1/routes
Headers: {"Accept":"application/json, text/plain, */*","Content-Type":"application/json"}
Data: {"success":false,"message":"java.lang.IllegalArgumentException: No enum constant com.alibaba.higress.sdk.model.route.RoutePredicateTypeEnum.","data":null}

查看higress-console 日志：
2024-09-18 03:10:22.753 ERROR 7 --- [nio-8080-exec-4] c.a.h.c.aop.ApiStandardizationAspect     : IllegalArgumentException occurs when calling com.alibaba.higress.console.controller.RoutesController.add

java.lang.IllegalArgumentException: No enum constant com.alibaba.higress.sdk.model.route.RoutePredicateTypeEnum.
	at java.base/java.lang.Enum.valueOf(Enum.java:273) ~[na:na]
	at com.alibaba.higress.sdk.model.route.RoutePredicateTypeEnum.valueOf(RoutePredicateTypeEnum.java:21) ~[higress-admin-sdk-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at com.alibaba.higress.sdk.service.kubernetes.KubernetesModelConverter.setQueryAnnotation(KubernetesModelConverter.java:1605) ~[higress-admin-sdk-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at com.alibaba.higress.sdk.service.kubernetes.KubernetesModelConverter.fillIngressMetadata(KubernetesModelConverter.java:1135) ~[higress-admin-sdk-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at com.alibaba.higress.sdk.service.kubernetes.KubernetesModelConverter.route2Ingress(KubernetesModelConverter.java:193) ~[higress-admin-sdk-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at com.alibaba.higress.sdk.service.RouteServiceImpl.add(RouteServiceImpl.java:78) ~[higress-admin-sdk-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
	at com.alibaba.higress.console.controller.RoutesController.add(RoutesController.java:58) ~[classes!/:0.0.1-SNAPSHOT]
	at com.alibaba.higress.console.controller.RoutesController$$FastClassBySpringCGLIB$$96f87c0d.invoke(<generated>) ~[classes!/:0.0.1-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.9.jar!/:5.3.9]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.3.9.jar!/:5.3.9]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.9.jar!/:5.3.9]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.9.jar!/:5.3.9]
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:123) ~[spring-context-5.3.9.jar!/:5.3.9]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.9.jar!/:5.3.9]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.9.jar!/:5.3.9]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.9.jar!/:5.3.9]
	at com.alibaba.higress.console.aop.ApiStandardizationAspect.intercept(ApiStandardizationAspect.java:78) ~[classes!/:0.0.1-SNAPSHOT]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[spring-aop-5.3.9.jar!/:5.3.9]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624) ~[spring-aop-5.3.9.jar!/:5.3.9]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72) ~[spring-aop-5.3.9.jar!/:5.3.9]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.9.jar!/:5.3.9]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.9.jar!/:5.3.9]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.9.jar!/:5.3.9]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.9.jar!/:5.3.9]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.9.jar!/:5.3.9]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.3.9.jar!/:5.3.9]
	at com.alibaba.higress.console.controller.RoutesController$$EnhancerBySpringCGLIB$$800bb2e6.add(<generated>) ~[classes!/:0.0.1-SNAPSHOT]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) ~[spring-web-5.3.9.jar!/:5.3.9]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) ~[spring-web-5.3.9.jar!/:5.3.9]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.3.9.jar!/:5.3.9]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.9.jar!/:5.3.9]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.9.jar!/:5.3.9]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.9.jar!/:5.3.9]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1064) ~[spring-webmvc-5.3.9.jar!/:5.3.9]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.9.jar!/:5.3.9]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.9.jar!/:5.3.9]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.9.jar!/:5.3.9]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.9.jar!/:5.3.9]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.52.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.9.jar!/:5.3.9]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.9.jar!/:5.3.9]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2024-09-18 03:10:45.811 ERROR 7 --- [-SecretLoader-0] c.a.h.c.controller.AiProxyController     : Secret higress-console does not contain service URL or token for ai-proxy.
2024-09-18 03:11:45.838 ERROR 7 --- [-SecretLoader-0] c.a.h.c.controller.AiProxyController     : Secret higress-console does not contain service URL or token for ai-proxy.

**Comment by YIwanT** [comment]
我也遇到了
是k8s 版本的问题吗？？？

**Comment by YIwanT** [comment]
Data: {"success":false,"message":"io.kubernetes.client.openapi.ApiException: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"admission webhook \\\"validate.ingress.ingress.kubernetes.io\\\" denied the request: template: nginx.tmpl:1091:24: executing \\\"SERVER\\\" at \\u003cgetIngressInformation $location.Ingress $server.Hostname $location.IngressPath\\u003e: error calling getIngressInformation: runtime error: invalid memory address or nil pointer dereference\",\"reason\":\"BadRequest\",\"code\":400}\n","data":null}

**Comment by CH3CHO** [comment]
你的K8s里是不是还装了nginx ingress？它可能不兼容Higress创建的ingress格式。

**Comment by YIwanT** [comment]
是的 我在两个集群里面安装了

**Comment by YIwanT** [comment]
一个是全新的集群，是正常的，一个是先装了 ingress 的集群 然后再安装集群 就出现问题了

**Comment by YIwanT** [comment]
另外就是 我测试发现 如果路由不带域名是正常的  添加域名才会出现报错

**Comment by CH3CHO** [comment]
> 一个是先装了 ingress 的集群 然后再安装集群

没看懂你这句话。是先安装了 nginx ingress 再安装 higress 吗？这个应该就是 nginx ingress 的兼容问题。你装的是什么版本，是最新的吗？可以考虑去那边提个 issue 问一下。

**Comment by CH3CHO** [comment]
nginx ingress 应该是给 Ingress 资源挂了 webhook 的，并且没有配置让 K8s 忽略报错。创建它不兼容的 Ingress 资源时，webhook 报错，导致创建失败。

**Comment by YIwanT** [comment]
好的 大概率应该是你的说 版本兼容问题 nginx ingress 我不太熟悉 我去研究下 谢谢解答
-------------
另外补充一下我的环境版本
我测试的 集群 v1.30.2  最新版的 higress  没有安装 nginx ingress  是正常使用的
集群 v1.26.1 最新版的 higress  安装了 nginx  ingress  出现问题

**Comment by CH3CHO** [comment]
下面是一个 Higress Console 创建出来的 Ingress 数据。它的配置方式和常规的 Ingress 略有差异。应该是 nginx 那边没有很好兼容。

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    higress.io/destination: home-service.default.svc.cluster.local:8080
    higress.io/ignore-path-case: "false"
  creationTimestamp: "2024-10-17T03:40:47Z"
  generation: 1
  labels:
    higress.io/resource-definer: higress
  name: home
  namespace: higress-system
  resourceVersion: "543407"
  uid: 03244b1a-11d5-400f-9ad4-b642dd63d35f
spec:
  ingressClassName: higress
  rules:
  - http:
      paths:
      - backend:
          resource:
            apiGroup: networking.higress.io
            kind: McpBridge
            name: default
        path: /
        pathType: Prefix
```

**Comment by YIwanT** [comment]
嘻嘻 我又来了，经过测试 测试 nginx ingress 的版本兼容问题 我这边的操作是 通过升级 nginx ingress 来处理
目前 nginx ingress 的版本是 v1.11.3
使用的镜像  registry.k8s.io/ingress-nginx/controller:v1.11.3
这个 issue 应该可以关闭 确认是版本的兼容问题
