### ISSUE TITLE
使用eureka注册中心，偶发性触发controller中的higress-core容器报空指针

### ISSUE THREAD

**Issue by lcfang** [alibaba/higress#1536]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [x] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
使用eureka注册中心，当修改eureka注册中心地址时，偶发性controller中的higress-core容器出现空指针的报错，导致容器重启

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:
![image](https://github.com/user-attachments/assets/626109c2-3579-41a8-ba25-f2b119790b67)

### Ⅲ. Describe what you expected to happen

希望能够正常进行新的注册中心订阅，并及时更新CDS信息
### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. helm安装v2.0.2版本的higress
2. 通过console配置eureka注册中心，可能配置多个（相同的域名，不同端口）
3. 过一会儿修改其中一个注册中心的端口，可能会触发以上报错

### Ⅵ. Environment:

- Higress version:  v2.0.2
- OS : kylin SP3
- Others: k8s v1.28

**Comment by lcfang** [comment]
看起来并不是由于修改注册中心地址的操作引起的报错，今天发现另一个测试环境里没有进行上面的操作，也出现了该容器重启，容器里报了上面的错误

**Comment by CH3CHO** [comment]
看了代码和报错信息，感觉不是 nil pointer，应该就是字面意思的 SEGV。有点诡异。 @johnlanni 有什么想法吗？

**Comment by johnlanni** [comment]
@CH3CHO 我也看了下逻辑，应该不是空指针

@lcfang 可以在你的环境下debug一下看看吗，比如在之前判断一下指针是否为空？以及GetApplication的地方也加一些日志

**Comment by CH3CHO** [comment]
![image](https://github.com/user-attachments/assets/324294ff-1da7-4f9d-9198-39a167522515)

根据这个 addr，被访问的指针应该不是 nil，不然 addr 就是 0 了。会不会是被 gc 了？

**Comment by lcfang** [comment]
> @lcfang 可以在你的环境下debug一下看看吗，比如在之前判断一下指针是否为空？以及GetApplication的地方也加一些日志
有个问题就是没有办法稳定复现，这个容器有debug日志级别调整开关吗？

**Comment by jiajinyuan** [comment]
# 该问题有解决方案吗？我遇到了同样问题：  Higress Controller 重启问题总结


## Ⅰ. 问题描述
`higress-controller` 中的 `higress-core` 容器会间歇性重启，表现为 Pod `Restart Count` 持续增长。

`kubectl get pod -A` 输出如下：

| NAMESPACE | NAME | READY | STATUS | RESTARTS | AGE |
| --- | --- | --- | --- | --- | --- |
| higress-system | higress-console-9759f65ff-9lsvx | 1/1 | Running | 1 (17d ago) | 17d |
| higress-system | higress-console-grafana-6f988755c6-8nwlx | 1/1 | Running | 0 | 9d |
| higress-system | higress-console-loki-7f69db796c-5tmc5 | 1/1 | Running | 1 (17d ago) | 17d |
| higress-system | higress-console-prometheus-65df7f8788-sc8mv | 1/1 | Running | 1 (17d ago) | 17d |
| higress-system | higress-controller-f79c468c4-vj8z8 | 2/2 | Running | 18 (4h27m ago) | 17d |
| higress-system | higress-gateway-689f6f5455-6pk5x | 2/2 | Running | 9 (11d ago) | 17d |
| higress-system | higress-gateway-689f6f5455-vfp7b | 2/2 | Running | 9 (11d ago) | 17d |

## Ⅱ. 排查过程
在本次排查中，`higress-core` 并非因为 OOM 或探针失败重启，而是运行时触发了 Go 的 nil pointer panic，进程直接退出后被 Kubernetes 拉起。

本次日志显示，重启前 `higress-core` 正在处理 Eureka / MCP 相关同步：

- 访问 `http://eureka-1.com:18081/eureka/apps/DWB-ORDER-SERVICE-DJR`
- 返回 `404`
- 随后出现 `unexpected end of JSON input`
- 最终触发 `panic: runtime error: invalid memory address or nil pointer dereference`

异常堆栈如下：

```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x312c99a]

goroutine 12827049 [running]:
github.com/alibaba/higress/v2/registry/eureka.(*watcher).subscribe.func1(0xc00251ff90?)
    github.com/alibaba/higress/v2/registry/eureka/watcher.go:211 +0x3a
github.com/alibaba/higress/v2/registry/eureka/client.(*Plan).watch(0xc00189e800, 0xc00122a540)
    github.com/alibaba/higress/v2/registry/eureka/client/plan.go:75 +0x135
created by github.com/alibaba/higress/v2/registry/eureka/client.NewPlan in goroutine 392
    github.com/alibaba/higress/v2/registry/eureka/client/plan.go:55 +0x107
```

问题点总结：

- `higress-core` 在 Eureka watcher 回调中对 `service.Instances` 直接解引用。
- Eureka 更新流在异常响应场景下可能传入空对象或异常结果。
- `McpBridge` 已启用 `eureka` 注册源，触发了这条代码路径。

## Ⅲ. 期望
当 Eureka 返回 404、空响应或异常 JSON 时，`higress-core` 应当忽略该次更新或记录错误，而不应 panic 退出。

## Ⅳ. 如何复现
1. 部署 Higress 2.2.1，并启用 `higress-controller`。
2. 配置 `McpBridge`，加入一个 `eureka` 注册源，例如 `eureka-1.com:18081`。
3. 让 Eureka 中某个应用返回 404 或异常空响应。
4. 观察 `higress-core` 日志，最终可复现 `nil pointer dereference` 并导致容器重启。

## Ⅴ. 环境：
Higress 版本：2.2.1
操作系统：Kubernetes 集群环境
其他：`higress-controller` 的 `higress-core` 容器在 Eureka/MCP 同步路径中触发 nil pointer panic；当前 `McpBridge` 中配置了 `eureka-1.com:18081`。

**Comment by ai-yang** [comment]
I would like to work on this issue.

The current update channel lifecycle provides a deterministic path to the reported nil application panic. Proposed scope:
- make `Plan.Stop` broadcast-based, non-blocking, and idempotent;
- stop the watcher when the update channel closes and skip nil application updates;
- add focused tests for closed update channels, nil applications, and concurrent repeated `Stop` calls;
- run the targeted package tests and race detector before opening the PR.

I will keep the change focused and link the PR back to this issue.
