### ISSUE TITLE
Higress Failed to connect to higress-console-grafana.higress-system/10.x.x.x:3000

### ISSUE THREAD

**Issue by gumutianqi** [alibaba/higress#403]
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
2023-06-28 08:07:18.040 ERROR 8 --- [e-Initializer-0] c.a.h.c.service.DashboardServiceImpl     : Error occurs when trying to initialize the dashboard.

com.alibaba.higress.console.controller.exception.BusinessException: Error occurs when loading dashboard info from Grafana.
        at com.alibaba.higress.console.service.DashboardServiceImpl.getBuiltInDashboardInfo(DashboardServiceImpl.java:201) ~[classes!/:0.0.1-SNAPSHOT]
        at com.alibaba.higress.console.service.DashboardServiceImpl.getDashboardInfo(DashboardServiceImpl.java:110) ~[classes!/:0.0.1-SNAPSHOT]
        at com.alibaba.higress.console.service.DashboardServiceImpl.initializeDashboard(DashboardServiceImpl.java:118) ~[classes!/:0.0.1-SNAPSHOT]
        at com.alibaba.higress.console.service.DashboardServiceImpl$DashboardInitializer.run(DashboardServiceImpl.java:242) ~[classes!/:0.0.1-SNAPSHOT]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.net.ConnectException: Failed to connect to higress-console-grafana.higress-system/10.x.x.x:3000
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108) ~[okhttp-3.14.9.jar!/:na]
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88) 
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. Install higress by helm with grafana and prometheus
2. open the higress console dashboard, then get the error page
3. Get some exception form the higress-console pod

### Ⅵ. Environment:

- Higress version:  1.0.1
- OS : Centos7.x
- Others: AWS EKS at region ap-southeast-1

**Comment by johnlanni** [comment]
cc @CH3CHO

**Comment by CH3CHO** [comment]
麻烦提供一下 higress-system ns 下面的各个 pod 的运行状态

**Comment by gumutianqi** [comment]
@CH3CHO 各个 pod 状态正常，进入 higress-console pod 内使用 telnet grafana 是可能正常通的。

```
NAME                                          READY   STATUS    RESTARTS   AGE
higress-console-5d6cd57895-fws6t              1/1     Running   0          15m
higress-console-grafana-75f7575c5-pclgw       1/1     Running   0          21m
higress-console-prometheus-668cdbb4cd-lnvt8   1/1     Running   0          17m
higress-controller-65c6bbb4dc-jhn97           2/2     Running   0          150m
higress-gateway-588b98f98d-2qqdt              1/1     Running   0          28h
higress-gateway-588b98f98d-qnmms              1/1     Running   0          3h35m
```

**Comment by gumutianqi** [comment]
目前把所有 pod 重启了一遍，观察到 higress-console 启动后有一个新的异常如下：

```

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.5.4)

2023-06-28 10:15:21.656  INFO 7 --- [           main] c.a.h.console.HigressConsoleApplication  : Starting HigressConsoleApplication v0.0.1-SNAPSHOT using Java 18.0.2.1 on higress-console-5d6cd57895-fws6t with PID 7 (/app/higress-console-0.0.1-SNAPSHOT.jar started by root in /app)
2023-06-28 10:15:21.658  INFO 7 --- [           main] c.a.h.console.HigressConsoleApplication  : No active profile set, falling back to default profiles: default
2023-06-28 10:15:22.735  INFO 7 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2023-06-28 10:15:22.742  INFO 7 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-06-28 10:15:22.743  INFO 7 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.52]
2023-06-28 10:15:22.780  INFO 7 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-06-28 10:15:22.780  INFO 7 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1075 ms
2023-06-28 10:15:23.010  INFO 7 --- [           main] c.a.h.c.s.k.KubernetesClientService      : init KubernetesClientService InCluster
2023-06-28 10:15:23.821  INFO 7 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2023-06-28 10:15:24.369  INFO 7 --- [           main] c.a.h.console.HigressConsoleApplication  : Started HigressConsoleApplication in 3.053 seconds (JVM running for 3.378)
2023-06-28 10:15:30.717  INFO 7 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-06-28 10:15:30.717  INFO 7 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-06-28 10:15:30.718  INFO 7 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2023-06-28 10:17:34.771  INFO 7 --- [nio-8080-exec-2] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x000xca0x010x000x000xc60x030x030xbc0x9c0xb0n+0x1f0x95W0xe00x1e0xc10x820xe60xf40xd6_0xf00xfe0x870xe20xaa0x860xaa0xbc0x13;P0xef0xd80xaf0xb70xbe0x000x00h0xcc0x140xcc0x130xc0/0xc0+0xc000xc0,0xc00x110xc00x070xc0'0xc0#0xc00x130xc00x090xc0(0xc0$0xc00x140xc00x0a0xcc0x150x000x9e0x000x9f0x00g0x00k0x0030x0090x000x9c0x000x9d0x000x050x000x040x00<0x00=0x00/0x0050xc00x120x000x160x000x0a0x000x030x000x080x000x060x000x140x000x110x000x190x000x170x0020xc00x080x000x120x000x130x000x150x0080x00@0x00f0x00j0x000xa20x000xa30x010x000x0050x000x050x000x050x010x000x000x000x000x000x0a0x000x080x000x060x000x170x000x180x000x190x000x0b0x000x020x010x000x000x0d0x000x0c0x000x0a0x040x010x040x030x020x010x020x030x020x020xff0x010x000x010x000x000x0f0x000x010x01...]. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:419) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:269) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.52.jar!/:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

**Comment by CH3CHO** [comment]
> higress-console-grafana.higress-system/10.x.x.x:3000

这个错误应该不影响的。那现在上面那个错误还有吗？

**Comment by gumutianqi** [comment]
@CH3CHO 　多次重启 console 和 grafana 这两个 pod 后，报错没有了，但是 Dashboard 页面还是没有正常显示，加载情况如下图：

![CleanShot-2023-06-29-r](https://github.com/alibaba/higress/assets/1057589/aa995dbb-c989-4a5d-b404-2631f647ffb2)

**Comment by CH3CHO** [comment]
请问这个Host关联的是Higress Gateway的IP还是Console的IP呢？如果是前者，那应该是可以的。如果是后者，那不行。。。

**Comment by gumutianqi** [comment]
@CH3CHO 意思是控制面板的域名要解析到 Higress-Gateway 这个 svc 上？

**Comment by gumutianqi** [comment]
@CH3CHO 目前调试的反馈：Grafana 面板不显示的问题是 ingress 路由的问题，我们的 Dashborad 是解析到内网 nlb 的，了解到目前的 Higress 版本的 Grafana 路由在 higress-gateway 这个 pod 上，而 higress-gateway 是公网入口 nlb，这两者就无法比较好的集成了。我们目前的打算是，采用自建 Grafana + Prometheus，然后 higress 监控采集的配置，手动在 Dashboard 上配置 Grafana 面板。

这个方案我们配置完成后再来反馈。

So this issue should close perhaps. Thanks @CH3CHO
